name: BioApp CI/CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm


      - name: Install dependencies
        run: npm ci


      - name: Build Quasar SPA
        run: npm run build



  deploy:

    needs: build

    if: github.event_name == 'push'

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm


      - name: Install dependencies
        run: npm ci


      - name: Build production
        run: npm run build


      - name: Deploy dist to o2switch
        uses: burnett01/rsync-deployments@7.0.2
        with:

          switches: -avzr --delete

          path: dist/spa/

          remote_path: ${{ secrets.SERVER_PATH }}

          remote_host: ${{ secrets.SERVER_HOST }}

          remote_user: ${{ secrets.SERVER_USER }}

          remote_key: ${{ secrets.SERVER_KEY }}