name: BioApp CI/CD

on:
  push:
    branches:
      - main


jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm


      - name: Install dependencies
        run: npm ci


      - name: Build Quasar SPA
        run: npm run build


      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: bioapp-dist
          path: dist/spa



  deploy:

    needs: build

    if: github.event_name == 'push'

    runs-on: ubuntu-latest

    steps:


      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: bioapp-dist
          path: dist/spa



      - name: Deploy BioApp using FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5

        with:

          server: ${{ secrets.FTP_SERVER }}

          username: ${{ secrets.FTP_USERNAME }}

          password: ${{ secrets.FTP_PASSWORD }}

          protocol: ftps

          port: 21

          server-dir: ${{ secrets.FTP_REMOTE_DIR }}

          local-dir: dist/spa/